### ISSUE TITLE
Work with Bob on getting slides into Google 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/k12#42]

**Comment by andrewlgiannakakis** [comment]
Hi there Britt, I spoke with Bob on the phone on my way home yesterday and basically, I learned that these are his resources that he's culled from other places over time, and he's fine with us using them. I told him I would probably just want to include some sort of "thank you Bob" language somewhere on the crosswalk (much like I did with Julie on the AP Bio one). I believe he'll be sending us the PPTs via Drive, and I told him that we'll embed the links on our side, just because I'm not sure yet of how or where I would want them embedded. And, I also am thinking to be safe, I might "re-create" them just in case they come with formatting weird or perhaps even with resources that might not actually be open. My hope here is that he'll send us what he has, and then we'll create something workable from there. :)
